### PR TITLE
fix extra word selected at the end when expanding selection in language without explicit word divider

### PR DESCRIPTION
**Pull request by aidenlx**
## Description of the Change

In [chinese word segmenter plugin](https://github.com/aidenlx/cm-chs-patch), I've extended the function of `wordAt` and `findWordAt` to allow Chinese paragraph, which lack explicit word divider, to be segmented correctly. 

However, in current version of smart md hotkey, to expand the selection, it first trim the selection to remove word divider from selection range, then use selection anchor and head to determine the exact word range for selection. It works fine in languages that use explicit word divider, but when selection is inside a paragraph without explicit word breaks, it may fail at some cases. 

For example, when `天气不错` ,which should be segmented into `天气` and `不错`, is selected like the following screenshot: 
image
expanded result will be the whole `天气不错`, because `wordAt` has trouble selecting whether the word at front or the one after when word divider is implicit (there is no divider(space char) in text, so it can't choose the word before it when cursor is at the beginning of divider, or the one after when at the end of divider) and always select the word after it unless the cursor is at the end of line

In this PR, I solve this problem by checking the word range when moving pos of head back one character and see if two results are the same. it should be the same when there are explicit word dividers, and if the results not the same, it will use the new result, which is desirable.

  ## Checklist
  - [x] Used the provided eslint configuration, [as explained in the Readme](README.md#Contribute).
  - [x] Did *not* use prettier.
  - [x] Used expressive variable names.
  - [x] Code is commented well.

### CODE REVIEW

**Comment by chrisgrieser** [comment]
Thanks for the PR!

I am wondering, wouldn't this be better tracked upstream, like Obsidian's API or even CodeMirror?

`Findatword` is used by a bunch of plugins after all.

**Comment by aidenlx** [comment]
that should be two issues: 

1. the segmenter issue for CJK languages [won't be fixed in upstream in short term](https://discuss.codemirror.net/t/about-the-selection-range-when-double-clicking-intl-segmenter/4241), therefore I've made monkey-patches around `wordAt` and other features in the plugin to make segmenter work almost painlessly. (With the plugin installed, the text expansion feature of smart-md-hotkeys works without any specific modifications in Chinese paragraph except the edge cases mentioned above)
2. The PR I've made aims to solve the edge case where `wordAt` can't select word before cursor with implicit word divider, and the solution is rather generic so it should also work when upstream solve the wordAt issue.

**Comment by chrisgrieser** [comment]
Hmm okay, I'm gonna merge this, but I hope you would answer any Chinese word related issues that might come up, cause I for sure won't be able to help with them 😅

**Comment by aidenlx** [comment]
sure thing! just ping me if you need any help

**Pull request merged**
